http:
  - scheme: http
    hostname: localhost:8080
    path: /
    method: get
    userAgent: healthcheckr/1.0/example
    timeoutMs: 3000
    expectStatusCode: 200
    expectBodyRegexes:
      - "200"
    intervalMs: 5000
    failureThreshold: 2
    channels:
      - telegram-default
      - slack-default
channels:
  - name: telegram-default
    type: telegram
    apiKey:
      fromEnv: TELEGRAM_BOT_TOKEN
    chatId:
      fromEnv: TELEGRAM_CHAT_ID
  - name: slack-default
    type: slack
    url:
      fromEnv: SLACK_WEBHOOK_URL
