http:
  - scheme: https
    hostname: asdasdasdasdafffff.com
    path: /
    queries:
      - aaa=bbb
      - bbb=ccc
    method: get
    userAgent: healthcheckr/1.0/example
    timeoutMs: 3000
    expectStatusCode: 200
    expectBodyRegexes:
      - Google
    intervalMs: 5000
    failureThreshold: 3
    channels:
      - telegram-default
      - slack-default
channels:
  - name: telegram-default
    type: telegram
    apiKey:
      fromEnv: TELEGRAM_BOT_TOKEN
    chatId:
      fromEnv: TELEGRAM_CHAT_ID
  - name: slack-default
    type: slack
    url:
      fromEnv: SLACK_WEBHOOK_URL
